const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const crypto = require('node:crypto')
const esbuild = require('esbuild')
const {Module} = require('node:module')
const root=path.resolve(__dirname,'..')
const m=new Module(__filename,module); m.paths=module.paths
m._compile(esbuild.buildSync({entryPoints:[path.join(root,'electron/services/macKeySupport.ts')],bundle:true,platform:'node',format:'cjs',packages:'external',write:false}).outputFiles[0].text,__filename)
const {parseMacKeyResult,getMacImageKey}=m.exports
const key='ab'.repeat(32)
assert.deepEqual(parseMacKeyResult(JSON.stringify({success:true,key})),{success:true,key})
assert.equal(parseMacKeyResult(JSON.stringify({success:true,key:'bad'})).success,false)
assert.equal(parseMacKeyResult(JSON.stringify({success:false,key})).success,false)
assert.equal(parseMacKeyResult(JSON.stringify({success:false,result:key})).success,false)
assert.equal(parseMacKeyResult('stderr SECRET '+key).success,false)
assert.match(parseMacKeyResult('ERROR:ATTACH_FAILED:task_for_pid:5').error,/系统拒绝/)
assert(!parseMacKeyResult('ERROR:'+key).error.includes(key))
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'weflow-mac-key-'))
try {
 const home=path.join(temporary,'home'), documents=path.join(temporary,'Documents')
 const first=path.join(documents,'xwechat_files','wxid_first_ab12'),second=path.join(documents,'xwechat_files','wxid_second')
 for(const dir of [first,second])fs.mkdirSync(path.join(dir,'msg','attach'),{recursive:true})
 const code=52494578
 const aes=crypto.createHash('md5').update(code+'wxid_first').digest('hex').slice(0,16)
 const plaintext=Buffer.from('89504e470d0a1a0a0000000d49484452','hex')
 const cipher=crypto.createCipheriv('aes-128-ecb',Buffer.from(aes,'ascii'),null); cipher.setAutoPadding(false)
 const image=Buffer.alloc(33);Buffer.from([7,8,86,50,8,7]).copy(image); Buffer.concat([cipher.update(plaintext),cipher.final()]).copy(image,15)
 image[31]=255^(code&255);image[32]=217^(code&255)
 fs.writeFileSync(path.join(first,'msg','attach','first_t.dat'),image)
 const cache=path.join(documents,'app_data','net','kvcomm');fs.mkdirSync(cache,{recursive:true})
 fs.writeFileSync(path.join(cache,`key_${code}_test.statistic`),'')
 const good=getMacImageKey(path.dirname(first),'wxid_first_ab12',undefined,home)
 assert.equal(good.success,true);assert.equal(good.aesKey,aes);assert.equal(good.verified,true);assert.equal(good.xorKey,code&255)
 assert.equal(getMacImageKey(path.dirname(first),'wxid_second',undefined,home).success,false)
 assert.equal(getMacImageKey(first,'wxid_second',undefined,home).success,false)
 assert.equal(getMacImageKey(path.dirname(first),undefined,undefined,home).success,false)
 fs.rmSync(path.join(first,'msg','attach','first_t.dat'))
 assert.equal(getMacImageKey(first,'wxid_first_ab12',undefined,home).success,false)
 fs.writeFileSync(path.join(first,'msg','attach','wrong_t.dat'),Buffer.alloc(33))
 assert.equal(getMacImageKey(first,'wxid_first_ab12',undefined,home).success,false)
 console.log('Mac key results: valid key, malformed/failed result, permission failure, redacted errors; cache derivation, suffix account, wrong-account rejection and missing/invalid template checks passed.')
}finally{fs.rmSync(temporary,{recursive:true,force:true})}
